### ISSUE TITLE
Exception Thread

### ISSUE THREAD

**Issue by Wanted135** [core-hacked/Discondelete#1]
Hello, issue when running #PS command.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\gateway.py", line 134, in run
    if self._last_recv + self.heartbeat_timeout < time.perf_counter():
TypeError: unsupported operand type(s) for +: 'float' and 'str'

**Comment by core-hacked** [comment]
Hi, I am currently looking into this issue, can you tell me how you called ``main.py`` did you provide arguments or did you just call it without any?

Thanks!

**Comment by core-hacked** [comment]
# Update:
### I have hopefully fixed the issue now and you should be ready to rock with Discondelete.
If anything else pops up, feel free to open another issue any time 😄
